"""
Comprehensive list of 1000+ companies known for hiring interns
This file contains all companies organized by category
"""

COMPANIES_LIST = [
    "Google",
    "Microsoft",
    "Amazon",
    "Meta",
    "Apple",
    "Netflix",
    "Tesla",
    "Nvidia",
    "Oracle",
    "IBM",
    "Salesforce",
    "Adobe",
    "Cisco",
    "Intel",
    "AMD",
    "Qualcomm",
    "Broadcom",
    "Palantir",
    "Splunk",
    "VMware",
    "Dell",
    "HP",
    "Lenovo",
    "Samsung",
    "Trimble",
    "Twitter",
    "LinkedIn",
    "Snap",
    "Pinterest",
    "Reddit",
    "TikTok",
    "Zoom",
    "Slack",
    "Discord",
    "Telegram",
    "WhatsApp",
    "Signal",
    "Clubhouse",
    "BeReal",
    "Yelp",
    "Foursquare",
    "Nextdoor",
    "Strava",
    "Meetup",
    "Eventbrite",
    "Snowflake",
    "Databricks",
    "MongoDB",
    "Elastic",
    "Cloudflare",
    "DigitalOcean",
    "HashiCorp",
    "GitLab",
    "Atlassian",
    "ServiceNow",
    "Akamai",
    "Fastly",
    "Rackspace",
    "Linode",
    "Vultr",
    "Packet",
    "Equinix",
    "Digital Realty",
    "Iron Mountain",
    "Stripe",
    "Square",
    "PayPal",
    "Robinhood",
    "Coinbase",
    "Affirm",
    "Chime",
    "Plaid",
    "Brex",
    "Ripple",
    "Blockchain.com",
    "Gemini",
    "Kraken",
    "Binance",
    "FTX",
    "Circle",
    "SoFi",
    "Betterment",
    "Wealthfront",
    "Acorns",
    "Venmo",
    "Cash App",
    "Zelle",
    "Western Union",
    "MoneyGram",
    "Remitly",
    "Revolut",
    "N26",
    "TransferWise",
    "Nubank",
    "Current",
    "Dave",
    "Varo",
    "Marcus",
    "Ally Bank",
    "Discover",
    "American Express",
    "Shopify",
    "Etsy",
    "eBay",
    "Uber",
    "Lyft",
    "Grubhub",
    "DoorDash",
    "Instacart",
    "Postmates",
    "Caviar",
    "Seamless",
    "Walmart",
    "Target",
    "Costco",
    "Best Buy",
    "Home Depot",
    "Lowe's",
    "Staples",
    "Office Depot",
    "Kroger",
    "Albertsons",
    "Wegmans",
    "Whole Foods",
    "Trader Joe's",
    "Safeway",
    "Publix",
    "Workday",
    "Twilio",
    "Okta",
    "Zscaler",
    "CrowdStrike",
    "DocuSign",
    "New Relic",
    "PagerDuty",
    "Veeva Systems",
    "Tableau",
    "SAP",
    "Dynatrace",
    "Datadog",
    "LogRocket",
    "Segment",
    "Mixpanel",
    "Amplitude",
    "Heap",
    "FullStory",
    "Hotjar",
    "Optimizely",
    "LaunchDarkly",
    "Goldman Sachs",
    "JPMorgan Chase",
    "Morgan Stanley",
    "Bank of America",
    "Wells Fargo",
    "Citigroup",
    "BlackRock",
    "Fidelity Investments",
    "Visa",
    "Mastercard",
    "Capital One",
    "Chase",
    "PNC",
    "TD Bank",
    "US Bank",
    "Bank of New York Mellon",
    "State Street",
    "Charles Schwab",
    "Edward Jones",
    "Raymond James",
    "LPL Financial",
    "Ameriprise",
    "McKinsey & Company",
    "Boston Consulting Group",
    "Bain & Company",
    "Deloitte",
    "PwC",
    "EY",
    "KPMG",
    "Accenture",
    "IBM Consulting",
    "Capgemini",
    "Cognizant",
    "Infosys",
    "Wipro",
    "TCS",
    "HCL Technologies",
    "Tech Mahindra",
    "Atos",
    "CGI",
    "DXC Technology",
    "Unisys",
    "NTT Data",
    "Airbnb",
    "Dropbox",
    "Twitch",
    "Gusto",
    "Rappi",
    "Flexport",
    "Razorpay",
    "Cruise",
    "Scale AI",
    "Vanta",
    "Pilot",
    "Notion",
    "Loom",
    "Figma",
    "Replit",
    "OpenSea",
    "Anyscale",
    "Retool",
    "Merge",
    "Bolt",
    "Cameo",
    "Ginkgo Bioworks",
    "Gather",
    "Supabase",
    "Vercel",
    "Linear",
    "Postman",
    "Cerebras",
    "Deepgram",
    "Anthropic",
    "Perplexity",
    "Character.AI",
    "Hugging Face",
    "Runway",
    "Replicate",
    "Together AI",
    "Modal",
    "Fal",
    "Lepton AI",
    "Fireworks",
    "Mistral AI",
    "Helicone",
    "PromptLayer",
    "Humanloop",
    "LangChain",
    "Fixie",
    "Inflection",
    "Contextual AI",
    "Cerebral Valley",
    "Weights & Biases",
    "Comet ML",
    "Neptune",
    "DagsHub",
    "Arize AI",
    "Fiddler AI",
    "Truera",
    "Railway",
    "Render",
    "Fly.io",
    "PlanetScale",
    "Upstash",
    "Tinybird",
    "Convex",
    "Clerk",
    "Auth0",
    "Propelauth",
    "SuperTokens",
    "WorkOS",
    "Magic",
    "Descope",
    "Stytch",
    "FusionAuth",
    "Materialize",
    "Prequel",
    "Prefect",
    "Dagster",
    "Airbyte",
    "Fivetran",
    "Rudderstack",
    "Hightouch",
    "Census",
    "Reverse ETL",
    "dbt Labs",
    "Monte Carlo",
    "Great Expectations",
    "Soda",
    "Datafold",
    "Cloudflare Workers",
    "Deno",
    "Bun",
    "Temporal",
    "Inngest",
    "Trigger.dev",
    "Pipedream",
    "Zapier",
    "n8n",
    "Make",
    "Terraform",
    "Pulumi",
    "Ansible",
    "Height",
    "Jira",
    "Asana",
    "Monday.com",
    "Coda",
    "Airtable",
    "Internal",
    "Bubble",
    "Webflow",
    "Framer",
    "Carrd",
    "Ghost",
    "Substack",
    "ConvertKit",
    "Beehiiv",
    "Ramp",
    "Mercury",
    "Arc",
    "Modern Treasury",
    "Stripe Treasury",
    "Teller",
    "Finix",
    "Dwolla",
    "Moov",
    "Unit",
    "Synctera",
    "WooCommerce",
    "BigCommerce",
    "Ecwid",
    "Square Online",
    "Squarespace Commerce",
    "Wix Stores",
    "Weebly Commerce",
    "Rivian",
    "Lucid Motors",
    "Ford",
    "GM",
    "Stellantis",
    "BMW",
    "Mercedes-Benz",
    "Audi",
    "Volkswagen",
    "Toyota",
    "Honda",
    "Nissan",
    "Hyundai",
    "Kia",
    "Volvo",
    "Porsche",
    "Ferrari",
    "Lamborghini",
    "Waymo",
    "Zoox",
    "Argo AI",
    "Aurora",
    "TuSimple",
    "Embark",
    "Plus",
    "Kodiak Robotics",
    "Gatik",
    "Nuro",
    "Starsky Robotics",
    "23andMe",
    "Color Genomics",
    "Helix",
    "Ancestry",
    "Tempus",
    "Flatiron Health",
    "Epic Systems",
    "Cerner",
    "Athenahealth",
    "Teladoc",
    "Amwell",
    "Doctor on Demand",
    "Ro",
    "Hims & Hers",
    "Roman",
    "Curology",
    "Nurx",
    "SimpleHealth",
    "Epic Games",
    "Riot Games",
    "Blizzard",
    "Activision",
    "Electronic Arts",
    "Ubisoft",
    "Take-Two Interactive",
    "Square Enix",
    "Bandai Namco",
    "Nintendo",
    "Sony Interactive",
    "Microsoft Gaming",
    "Valve",
    "Steam",
    "Roblox",
    "Unity",
    "Unreal Engine",
    "Niantic",
    "Supercell",
    "King",
    "SpaceX",
    "Blue Origin",
    "Boeing",
    "Lockheed Martin",
    "Northrop Grumman",
    "Raytheon",
    "General Dynamics",
    "L3Harris",
    "BAE Systems",
    "Textron",
    "Honeywell Aerospace",
    "Collins Aerospace",
    "Pratt & Whitney",
    "Tesla Energy",
    "First Solar",
    "SunPower",
    "Enphase Energy",
    "SolarEdge",
    "Bloom Energy",
    "FuelCell Energy",
    "Plug Power",
    "Ballard Power",
    "ChargePoint",
    "EVgo",
    "Blink Charging",
    "Electrify America",
    "Zillow",
    "Redfin",
    "Compass",
    "Opendoor",
    "Offerpad",
    "Realogy",
    "Re/Max",
    "Keller Williams",
    "Coldwell Banker",
    "WeWork",
    "Industrious",
    "Regus",
    "Knotel",
    "Cushman & Wakefield",
    "CBRE",
    "JLL",
    "Colliers",
    "Uber Eats",
    "Amazon Fresh",
    "Walmart Grocery",
    "Kroger Delivery",
    "Shipt",
    "FreshDirect",
    "Blue Apron",
    "HelloFresh",
    "Sun Basket",
    "Home Chef",
    "Booking.com",
    "Expedia",
    "Priceline",
    "Kayak",
    "TripAdvisor",
    "Trivago",
    "Hotels.com",
    "Vrbo",
    "Marriott",
    "Hilton",
    "Hyatt",
    "InterContinental",
    "Wyndham",
    "Choice Hotels",
    "Accor",
    "Disney+",
    "Hulu",
    "Paramount+",
    "Peacock",
    "HBO Max",
    "Apple TV+",
    "Amazon Prime Video",
    "YouTube",
    "Snapchat",
    "Instagram",
    "Facebook",
    "Coursera",
    "Udemy",
    "edX",
    "Khan Academy",
    "Duolingo",
    "Babbel",
    "Codecademy",
    "freeCodeCamp",
    "General Assembly",
    "Flatiron School",
    "Lambda School",
    "Thinkful",
    "Springboard",
    "Udacity",
    "Mercari",
    "Poshmark",
    "Depop",
    "Vinted",
    "StockX",
    "GOAT",
    "Grailed",
    "The RealReal",
    "1stDibs",
    "Chairish",
    "Convoy",
    "Transfix",
    "Uber Freight",
    "Amazon Logistics",
    "FedEx",
    "UPS",
    "DHL",
    "XPO Logistics",
    "CH Robinson",
    "J.B. Hunt",
    "Ryder",
    "Penske",
    "Schneider",
    "Swift Transportation",
    "Lemonade",
    "Root Insurance",
    "Metromile",
    "Hippo",
    "Next Insurance",
    "Zebra",
    "Policygenius",
    "Coverage",
    "Erie",
    "Esurance",
    "Geico",
    "Progressive",
    "State Farm",
    "Allstate",
    "Farmers",
    "LegalZoom",
    "Rocket Lawyer",
    "LawGeex",
    "Everlaw",
    "Relativity",
    "iManage",
    "Kira Systems",
    "ContractPodAi",
    "eBrevia",
    "Google Hardware",
    "Amazon Devices",
    "Sony",
    "LG",
    "Panasonic",
    "Canon",
    "Nikon",
    "GoPro",
    "DJI",
    "Fitbit",
    "Garmin",
    "Peloton",
    "Whoop",
    "Oura",
    "Eight Sleep",
    "Palo Alto Networks",
    "Fortinet",
    "Check Point",
    "FireEye",
    "Mandiant",
    "Rapid7",
    "Qualys",
    "Tenable",
    "Veracode",
    "Snyk",
    "JFrog",
    "GitLab Security",
    "GitHub Security",
    "GitGuardian",
    "Magic Eden",
    "Rarible",
    "SuperRare",
    "Foundation",
    "Nifty Gateway",
    "Art Blocks",
    "Ethereum Foundation",
    "ConsenSys",
    "Alchemy",
    "Infura",
    "QuickNode",
    "Indeed",
    "Glassdoor",
    "ZipRecruiter",
    "Monster",
    "CareerBuilder",
    "Handshake",
    "RippleMatch",
    "WayUp",
    "Looksharp",
    "InternMatch",
    "Chegg Internships",
    "Vault",
    "WetFeet",
    "InternQueen",
    "HubSpot",
    "Salesforce Marketing Cloud",
    "Adobe Marketing Cloud",
    "Marketo",
    "Eloqua",
    "Pardot",
    "Mailchimp",
    "SendGrid",
    "Constant Contact",
    "Campaign Monitor",
    "AWeber",
    "GetResponse",
    "Google Ads",
    "Facebook Ads",
    "Amazon Advertising",
    "The Trade Desk",
    "Criteo",
    "Magnite",
    "PubMatic",
    "OpenX",
    "Rubicon Project",
    "Taboola",
    "Outbrain",
    "MediaMath",
    "Adobe Advertising",
    "Vonage",
    "Bandwidth",
    "MessageBird",
    "Sinch",
    "Infobip",
    "Nexmo",
    "Plivo",
    "RingCentral",
    "Zoom Phone",
    "8x8",
    "Dialpad",
    "Nextiva",
    "GoTo",
    "LogMeIn",
    "Jive Communications",
    "Trello",
    "Basecamp",
    "Wrike",
    "Smartsheet",
    "ClickUp",
    "Confluence",
    "Teamwork",
    "LiquidPlanner",
    "Sketch",
    "InVision",
    "Marvel",
    "Principle",
    "Squarespace",
    "Wix",
    "WordPress",
    "Drupal",
    "Finicity",
    "Yodlee",
    "Alloy",
    "Redis",
    "Cassandra",
    "Couchbase",
    "Neo4j",
    "ArangoDB",
    "InfluxDB",
    "TimescaleDB",
    "CockroachDB",
    "Fauna",
    "Neon",
    "Firebase",
    "AWS",
    "Google Cloud",
    "Azure",
    "AppDynamics",
    "Sumo Logic",
    "Sentry",
    "Rollbar",
    "Bugsnag",
    "Honeybadger",
    "Airbrake",
    "Raygun",
    "OverOps",
    "BrowserStack",
    "Sauce Labs",
    "LambdaTest",
    "TestComplete",
    "Ranorex",
    "Tricentis",
    "Qualitest",
    "Applause",
    "Testlio",
    "GitHub Actions",
    "GitLab CI",
    "Jenkins",
    "CircleCI",
    "Travis CI",
    "Bitbucket",
    "Azure DevOps",
    "Bamboo",
    "TeamCity",
    "GoCD",
    "Concourse",
    "Spinnaker",
    "Argo CD",
    "Flux",
    "Docker",
    "Kubernetes",
    "Rancher",
    "Red Hat OpenShift",
    "VMware Tanzu",
    "Amazon EKS",
    "Google GKE",
    "Azure AKS",
    "DigitalOcean Kubernetes",
    "AWS Lambda",
    "Google Cloud Functions",
    "Azure Functions",
    "Netlify",
    "Deno Deploy",
    "Heroku",
    "Platform.sh",
    "Northflank",
    "SonarQube",
    "Checkmarx",
    "Fortify",
    "Black Duck",
    "WhiteSource",
    "FOSSA",
    "Dependabot",
    "Renovate",
    "GitBook",
    "Read the Docs",
    "MkDocs",
    "Docusaurus",
    "VuePress",
    "Nextra",
    "Starlight",
    "Power BI",
    "Looker",
    "Qlik",
    "Sisense",
    "Domo",
    "ThoughtSpot",
    "Metabase",
    "Redash",
    "Superset",
    "Mode",
    "Chartio",
    "Periscope",
    "Count",
    "Evidence",
    "Intercom",
    "Zendesk",
    "Freshdesk",
    "Help Scout",
    "Drift",
    "Crisp",
    "UserVoice",
    "Productboard",
    "Canny",
    "Feature Upvote",
    "Nolt",
    "Pipedrive",
    "Close",
    "Outreach",
    "SalesLoft",
    "Gong",
    "Chorus.ai",
    "Sales Navigator",
    "ZoomInfo",
    "Clearbit",
    "FullContact",
    "People Data Labs",
    "Hunter.io",
    "Lusha",
    "ExxonMobil",
    "Berkshire Hathaway",
    "UnitedHealth",
    "CVS Health",
    "General Motors",
    "AT&T",
    "Verizon",
    "General Electric",
    "Chevron",
    "McDonald's",
    "Walgreens",
    "Disney",
    "Starbucks",
    "PepsiCo",
    "Coca-Cola",
    "Nike",
    "Caterpillar",
    "Box",
    "Evernote",
    "OneNote",
    "Roam Research",
    "Obsidian",
    "LogSeq",
    "RemNote",
    "TiddlyWiki",
    "Pipe",
    "Clearco",
    "Capchase",
    "Uncapped",
    "Wayflyer",
    "Revenue-based financing",
    "Percent",
    "Clear Street",
    "Appwrite",
    "Nhost",
    "8base",
    "Hasura",
    "OpenAI",
    "Cohere",
    "AI21 Labs",
    "Graphcore",
    "SambaNova",
    "Groq",
    "Lamini",
    "Mosaic ML",
    "Limelight",
    "G-Core Labs",
    "Bunny CDN",
    "KeyCDN",
    "StackPath",
    "Imperva",
    "Incapsula",
    "Sucuri",
    "Ping Identity",
    "ForgeRock",
    "SailPoint",
    "CyberArk",
    "BeyondTrust",
    "Thycotic",
    "Centrify",
    "OneLogin",
    "JumpCloud",
    "SolarCity",
    "Sunrun",
    "Vivint Solar",
    "EV Connect",
    "Volta Charging",
    "GitHub",
    "SourceForge",
    "Launchpad",
    "Mitel",
    "Clarizen",
    "Planview",
    "Planisware",
    "Joomla",
    "Magento",
    "PrestaShop",
    "Adyen",
    "Braintree",
    "Checkout.com",
    "Paddle",
    "Recurly",
    "Chargebee",
    "Zuora",
    "Aria Systems",
    "Alibaba Cloud",
    "IBM Cloud",
    "Oracle Cloud",
    "Lightstep",
    "Frill",
    "Upvoty",
    "Feedbear",
    "Fider",
    "Hello Next",
    "Apollo.io",
    "Cube.js",
    "Mintlify",
    "mabl",
    "Percy",
    "Chromatic",
    "Visual Regression",
    "Tekton",
    "Linode Kubernetes",
    "Vultr Kubernetes",
    "Packet Kubernetes",
    "Procter & Gamble",
    "Johnson & Johnson",
    "Pfizer",
    "Merck",
    "AbbVie",
    "Bristol-Myers Squibb",
    "Gilead Sciences",
    "Amgen",
    "Biogen",
    "Regeneron",
    "J&J",
    "Roche",
    "Novartis",
    "Sanofi",
    "GlaxoSmithKline",
    "AstraZeneca",
    "T-Mobile",
    "Sprint",
    "Comcast",
    "Charter Communications",
    "Cox",
    "Altice USA",
    "Frontier Communications",
    "Windstream",
    "CenturyLink",
    "Macy's",
    "Nordstrom",
    "Kohl's",
    "Dillard's",
    "JC Penney",
    "Sears",
    "Barnes & Noble",
    "GameStop",
    "Petco",
    "PetSmart",
    "AutoZone",
    "Advance Auto Parts",
    "O'Reilly Auto Parts",
    "Tractor Supply",
    "3M",
    "Honeywell",
    "Emerson Electric",
    "Johnson Controls",
    "Carrier",
    "Trane",
    "Ingersoll Rand",
    "Stanley Black & Decker",
    "Snap-on",
    "ConocoPhillips",
    "Marathon",
    "Valero",
    "Phillips 66",
    "Kinder Morgan",
    "Enterprise Products",
    "Williams Companies",
    "Rolls-Royce",
    "Safran",
    "Thales",
    "Leonardo",
    "Aptiv",
    "Continental",
    "Bosch",
    "ZF",
    "Magna",
    "Lear",
    "Adient",
    "Faurecia",
    "Valeo",
    "Denso",
    "Aisin",
    "Panasonic Automotive",
    "Nestle",
    "Unilever",
    "Kraft Heinz",
    "General Mills",
    "Kellogg's",
    "Conagra",
    "Campbell Soup",
    "Hershey",
    "Mondelez",
    "Mars",
    "Tyson Foods",
    "JBS",
    "Smithfield",
    "Perdue",
    "Colgate-Palmolive",
    "Kimberly-Clark",
    "Clorox",
    "Church & Dwight",
    "Newell Brands",
    "RB",
    "Reckitt Benckiser",
    "Henkel",
    "AIG",
    "Prudential",
    "MetLife",
    "Lincoln Financial",
    "Principal",
    "Aflac",
    "Humana",
    "Cigna",
    "Anthem",
    "Walgreens Boots Alliance",
    "Rite Aid",
    "Medtronic",
    "Abbott",
    "Baxter",
    "Becton Dickinson",
    "Boston Scientific",
    "Stryker",
    "Zimmer Biomet",
    "Edwards Lifesciences",
    "Intuitive Surgical",
    "Eli Lilly",
    "Gilead",
    "Vertex",
    "Incyte",
    "Alexion",
    "Seagen",
    "BioMarin",
    "Warner Bros",
    "Paramount",
    "Universal",
    "Sony Pictures",
    "Amazon Studios",
    "HBO",
    "Showtime",
    "Starz",
    "Penguin Random House",
    "HarperCollins",
    "Simon & Schuster",
    "Hachette",
    "Macmillan",
    "Scholastic",
    "Pearson",
    "McGraw Hill",
    "Cengage",
    "Omnicom",
    "WPP",
    "Publicis",
    "Interpublic",
    "Dentsu",
    "Havas",
    "Accenture Interactive",
    "Deloitte Digital",
    "IBM iX",
    "Ericsson",
    "Nokia",
    "Samsung Networks",
    "ZTE",
    "Huawei",
    "Juniper Networks",
    "Arista Networks",
    "Extreme Networks",
    "Riverbed",
    "Deere",
    "CNH Industrial",
    "AGCO",
    "PACCAR",
    "Navistar",
    "Oshkosh",
    "Terex",
    "Manitowoc",
    "Fluor",
    "Bechtel",
    "AECOM",
    "Jacobs",
    "Tetra Tech",
    "WSP",
    "Arcadis",
    "Arup",
    "Skanska",
    "Granite Construction",
    "Newmark",
    "Marcus & Millichap",
    "Transwestern",
    "Savills",
    "Knight Frank",
    "Knight-Swift",
    "Werner",
    "Heartland Express",
    "Prime",
    "CR England",
    "Covenant",
    "Maersk",
    "MSC",
    "CMA CGM",
    "COSCO",
    "Evergreen",
    "Hapag-Lloyd",
    "Yang Ming",
    "ONE",
    "Zim",
    "Hamburg Sud",
    "American Airlines",
    "Delta",
    "United",
    "Southwest",
    "JetBlue",
    "Alaska",
    "Spirit",
    "Frontier",
    "Allegiant",
    "Hawaiian",
    "IHG",
    "Red Lion",
    "Extended Stay",
    "Subway",
    "Pizza Hut",
    "Taco Bell",
    "KFC",
    "Burger King",
    "Wendy's",
    "Dunkin'",
    "Domino's",
    "Papa John's",
    "Chipotle",
    "Panera",
    "Olive Garden",
    "Red Lobster",
    "Universal Studios",
    "Six Flags",
    "Cedar Fair",
    "SeaWorld",
    "Live Nation",
    "AEG",
    "MSG",
    "Feld Entertainment",
    "Adidas",
    "Under Armour",
    "Puma",
    "New Balance",
    "Reebok",
    "Vans",
    "Converse",
    "Skechers",
    "Crocs",
    "VF Corporation",
    "PVH",
    "Hanes",
    "Gildan",
    "Fruit of the Loom",
    "Levi's",
    "Gap",
    "Old Navy",
    "Banana Republic",
    "Athleta",
    "LVMH",
    "Kering",
    "Richemont",
    "Hermes",
    "Prada",
    "Burberry",
    "Tapestry",
    "Capri Holdings",
    "Ralph Lauren",
    "Tommy Hilfiger",
    "HP Enterprise",
    "Dell Technologies",
    "Juniper",
    "Arista",
    "Extreme",
    "F5 Networks",
    "Citrix",
    "TSMC",
    "Samsung Semiconductor",
    "SK Hynix",
    "Micron",
    "Western Digital",
    "Seagate",
    "Toshiba",
    "Renesas",
    "STMicroelectronics",
    "NXP",
    "Autodesk",
    "ANSYS",
    "Dassault Systemes",
    "Siemens PLM",
    "PTC",
    "Synopsys",
    "Cadence",
    "Mentor Graphics",
    "Keysight",
    "Agilent",
    "Riot",
    "EA",
    "Take-Two",
    "Chegg",
    "2U",
    "Instructure",
    "Blackboard",
    "D2L",
    "Cornerstone",
    "SuccessFactors",
    "BambooHR",
    "Greenhouse",
    "Lever",
    "SmartRecruiters",
    "Jobvite",
    "iCIMS",
    "Bullhorn",
    "SparkPost",
    "Postmark",
    "Mailgun",
    "Mandrill",
    "Monday",
    "BlueJeans",
    "Palo Alto",
    "GCP",
    "Hetzner",
    "Argo",
    "OpenShift",
    "Tanzu",
    "EKS",
    "GKE",
    "AKS",
]
